/* Loose Ends — production workspace runtime (no demo data) */
(function () {
  'use strict';
  var SB=window.LESupabase||null,KEY='loose_ends_v31_state';
  var state={view:'overview',query:'',workspaceId:null,user:null,loaded:false,customers:[],opportunities:[],looseEnds:[],appointments:[],tasks:[],documents:[],followUps:[],recovered:0,loading:true,error:null};
  var content;
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function money(v){return '$'+Number(v||0).toLocaleString(undefined,{maximumFractionDigits:0});}
  function toast(msg){var e=document.getElementById('toast');if(!e)return;e.textContent=msg;e.className='toast show';setTimeout(function(){e.className='toast';},2200);}
  function nameOf(c){return c?([c.first_name,c.last_name].filter(Boolean).join(' ')||c.name||'Customer'):'Customer';}
  function customerMap(){var m={};state.customers.forEach(function(c){m[c.id]=c;});return m;}
  function priorityLabel(v){if(typeof v==='number')return v>=90?'Critical':v>=70?'High':v>=40?'Medium':'Low';var s=String(v||'medium').toLowerCase();return s==='critical'?'Critical':s==='high'?'High':s==='low'?'Low':'Medium';}
  function normalizeOpp(o){var c=o.customers||customerMap()[o.customer_id];return {id:o.id,type:o.source||o.title||'Opportunity',customer:nameOf(c),customerId:o.customer_id,phone:c&&c.phone||'',vehicle:o.vehicle||'',amount:Number(o.amount||0),priority:priorityLabel(o.priority),source:o.source||'Opportunity',reason:o.reason||'Revenue opportunity requiring attention.',next:'Review and choose the next best action.',status:o.status||'open',db:true,opportunityId:o.id};}
  function normalizeLoose(o){var c=o.customers||customerMap()[o.customer_id];return {id:o.opportunity_id||o.id,looseId:o.id,opportunityId:o.opportunity_id||null,type:o.source_entity||'Loose End',customer:nameOf(c),customerId:o.customer_id,phone:c&&c.phone||'',vehicle:o.vehicle||'',amount:Number(o.amount||0),priority:priorityLabel(o.priority),source:o.source_entity||'Recovery signal',reason:o.reason||'Revenue opportunity requiring attention.',next:o.recommended_action||'Review and choose the next best action.',status:o.status||'open',db:true};}
  function persist(){try{localStorage.setItem(KEY,JSON.stringify({view:state.view,query:state.query}));}catch(e){}}
  function loadLocal(){try{var x=JSON.parse(localStorage.getItem(KEY)||'null');if(x){state.view=x.view||'overview';state.query=x.query||'';}}catch(e){}}
  function workspace(){return SB.from('workspace_members').select('workspace_id').eq('user_id',state.user.id).limit(1).maybeSingle();}
  async function refresh(){
    state.loading=true;state.error=null;render();
    if(!SB){state.loading=false;state.error='Supabase is not configured.';render();return;}
    try{
      var ur=await SB.auth.getUser();state.user=ur&&ur.data&&ur.data.user;
      if(!state.user){state.loading=false;state.error='Sign in to access your business workspace.';render();return;}
      var wm=await workspace();state.workspaceId=wm&&wm.data&&wm.data.workspace_id;
      if(!state.workspaceId){state.loading=false;state.error='Your account is not connected to a workspace yet.';render();return;}
      var w=state.workspaceId;
      var rs=await Promise.all([
        SB.from('customers').select('*').eq('workspace_id',w).order('updated_at',{ascending:false}).limit(500),
        SB.from('opportunities').select('*,customers(first_name,last_name,phone)').eq('workspace_id',w).order('updated_at',{ascending:false}).limit(500),
        SB.from('loose_ends').select('*,customers(first_name,last_name,phone)').eq('workspace_id',w).eq('status','open').order('score',{ascending:false}).limit(500),
        SB.from('appointments').select('*').eq('workspace_id',w).order('starts_at',{ascending:true}).limit(100),
        SB.from('tasks').select('*').eq('workspace_id',w).order('due_at',{ascending:true}).limit(100),
        SB.from('documents').select('*').eq('workspace_id',w).order('created_at',{ascending:false}).limit(100),
        SB.from('follow_ups').select('*').eq('workspace_id',w).order('scheduled_at',{ascending:true}).limit(100),
        SB.from('opportunities').select('recovered_amount,status').eq('workspace_id',w).eq('status','recovered').limit(500)
      ]);
      var bad=rs.find(function(r){return r&&r.error;});if(bad)throw bad.error;
      state.customers=rs[0].data||[];state.opportunities=(rs[1].data||[]).map(normalizeOpp);state.looseEnds=(rs[2].data||[]).map(normalizeLoose);
      state.appointments=rs[3].data||[];state.tasks=rs[4].data||[];state.documents=rs[5].data||[];state.followUps=rs[6].data||[];
      state.recovered=(rs[7].data||[]).reduce(function(n,o){return n+Number(o.recovered_amount||0);},0);
      if(state.looseEnds.length)state.opportunities=state.looseEnds.concat(state.opportunities.filter(function(o){return !state.looseEnds.some(function(l){return l.opportunityId&&l.opportunityId===o.id;});}));
      state.loaded=true;state.loading=false;render();
    }catch(e){console.error('Loose Ends live load failed',e);state.loading=false;state.error=e.message||'Unable to load workspace data.';render();}
  }
  function head(a,b,c){return '<div class="page-head"><div><div class="eyebrow">'+esc(a)+'</div><div class="title">'+esc(b)+'</div><div class="subtitle">'+esc(c)+'</div></div><div class="date">'+(state.loaded?'LIVE WORKSPACE':'CONNECTING')+'</div></div>';}
  function kpi(l,v,n,t,i,w){return '<div class="card kpi"><div class="kpi-top"><div class="kpi-icon">'+i+'</div>'+esc(l)+'</div><div class="kpi-value">'+esc(v)+'</div><div class="kpi-note">'+esc(n)+'</div><div class="trend '+(w?'amber':'')+'">'+esc(t)+'</div></div>';}
  function empty(a,b){return '<div class="card" style="padding:28px;text-align:center"><h3>'+esc(a)+'</h3><p class="subtitle">'+esc(b)+'</p></div>';}
  function rows(list){return list.slice(0,8).map(function(o){return '<div class="opp-row"><div><span class="type">'+esc(o.type)+'</span></div><div><div class="customer-name">'+esc(o.customer)+'</div><div class="customer-meta">'+esc(o.reason)+'</div></div><div></div><div class="amount">'+money(o.amount)+'</div><div><span class="priority '+(o.priority==='High'||o.priority==='Critical'?'high':'medium')+'">'+esc(o.priority)+'</span></div><button class="action" onclick="LE.openOpp(\''+esc(o.id)+'\')">Take action</button></div>';}).join('');}
  function dashboard(){var open=state.opportunities.reduce(function(n,o){return n+Number(o.amount||0);},0);return '<div class="page">'+head('COMMAND CENTER','Run the business. Recover the money.','Live workspace data across customers, sales, scheduling, documents, tasks, and revenue recovery.')+'<div class="grid4">'+kpi('Recoverable revenue',money(open),'Open opportunity value','Live','◉')+kpi('Revenue recovered',money(state.recovered),'Recorded recovered amount','Live','✓')+kpi('Open loose ends',String(state.looseEnds.length),'Recovery signals requiring action','Live','⌁',state.looseEnds.length>0)+kpi('Customers',String(state.customers.length),'Customers in this workspace','Live','♙')+'</div><div class="two-col"><div class="card section-card"><div class="section-head"><div><div class="section-title">Priority revenue queue</div><div class="section-sub">Highest-value live opportunities.</div></div><button class="link-btn" onclick="LE.setView(\'loose\')">View all →</button></div>'+(rows(state.opportunities.slice().sort(function(a,b){return b.amount-a.amount;}))||empty('No open opportunities','New opportunities and recovery signals will appear here automatically.'))+'</div><div class="side-stack"><div class="card section-card"><div class="section-title">Today</div><div class="action-list"><div class="action-card"><div class="action-ico">◷</div><div><strong>Appointments</strong><small>Scheduled in this workspace</small></div><span class="mini-number">'+state.appointments.length+'</span></div><div class="action-card"><div class="action-ico">✓</div><div><strong>Open tasks</strong><small>Work that still needs an owner</small></div><span class="mini-number">'+state.tasks.filter(function(t){return t.status==='open';}).length+'</span></div><div class="action-card"><div class="action-ico">↻</div><div><strong>Follow-ups</strong><small>Scheduled customer actions</small></div><span class="mini-number">'+state.followUps.length+'</span></div></div></div><div class="card section-card"><div class="section-title">Workspace status</div><p class="subtitle">'+(state.loaded?'Live Supabase workspace connected.':state.error||'Connecting to workspace…')+'</p><button class="action" onclick="LE.refresh()">Refresh data</button></div></div></div></div>';}
  function loose(){var q=String(state.query||'').toLowerCase();var list=state.opportunities.filter(function(o){return !q||JSON.stringify(o).toLowerCase().indexOf(q)>=0;}).sort(function(a,b){return b.amount-a.amount;});return '<div class="page">'+head('RECOVERY ENGINE','Loose Ends','Every unfinished revenue event becomes a prioritized next action.')+'<div class="card recovery-banner"><div><div class="eyebrow">LIVE QUEUE</div><strong>'+money(list.reduce(function(n,o){return n+Number(o.amount||0);},0))+'</strong><span>'+list.length+' matching open opportunities</span></div><button class="primary" onclick="LE.refresh()">Refresh →</button></div><div class="toolbar"><input id="queueSearch" class="input" placeholder="Search live opportunities…" value="'+esc(state.query)+'"></div><div class="queue">'+(list.length?list.map(function(o){return '<div class="card queue-card"><div class="priority-strip"></div><div class="queue-main"><h3>'+esc(o.type)+' · '+esc(o.customer)+'</h3><p>'+esc(o.reason)+'</p><div class="queue-meta"><span>'+esc(o.source)+'</span><span>'+esc(o.status)+'</span></div></div><div class="queue-value"><strong>'+money(o.amount)+'</strong><small>'+esc(o.priority)+' priority</small><button class="action" onclick="LE.openOpp(\''+esc(o.id)+'\')">Review opportunity</button></div></div>';}).join(''):empty('Nothing is loose right now','That is good news. When a recoverable opportunity appears, it will show up here.'))+'</div></div>';}
  function customers(){var q=String(state.query||'').toLowerCase();var list=state.customers.filter(function(c){return !q||JSON.stringify(c).toLowerCase().indexOf(q)>=0;});return '<div class="page">'+head('CRM','Customers','One customer record shared across the operating system.')+'<div class="card"><div class="section-head"><div><div class="section-title">Customer 360</div><div class="section-sub">Live records from this workspace.</div></div></div>'+(list.length?'<table class="customer-table"><thead><tr><th>Customer</th><th>Phone</th><th>Email</th><th>Created</th></tr></thead><tbody>'+list.map(function(c){return '<tr><td><strong>'+esc(nameOf(c))+'</strong></td><td>'+esc(c.phone||'—')+'</td><td>'+esc(c.email||'—')+'</td><td>'+esc(c.created_at?new Date(c.created_at).toLocaleDateString():'—')+'</td></tr>';}).join('')+'</tbody></table>':empty('No customers yet','Add your first customer to begin building the shared customer record.'))+'</div></div>';}
  function recovery(){var total=state.opportunities.reduce(function(n,o){return n+Number(o.amount||0);},0);var rate=state.recovered+total?Math.round(state.recovered/(state.recovered+total)*100):0;return '<div class="page">'+head('RECOVERY','Revenue Recovery','Turn identified opportunities into action and recovered revenue.')+'<div class="grid4">'+kpi('Open opportunities',String(state.opportunities.length),'Live revenue opportunities','Live','◈')+kpi('Recovered',money(state.recovered),'Recorded recovery amount','Live','✓')+kpi('Follow-ups',String(state.followUps.length),'Scheduled customer actions','Live','↻')+kpi('Recovery rate',rate+'%','Recovered / identified','Live','◎')+'</div><div style="margin-top:14px">'+(state.opportunities.length?'<div class="card sequence"><div class="section-title">Active recovery work</div><div class="section-sub">Prioritized from live workspace data.</div>'+state.opportunities.slice(0,10).map(function(o,i){return '<div class="step"><div class="step-num">'+(i+1)+'</div><div><h4>'+esc(o.customer)+'</h4><p>'+esc(o.type)+' · '+money(o.amount)+' · '+esc(o.reason)+'</p></div><button class="action" onclick="LE.openOpp(\''+esc(o.id)+'\')">Open</button></div>';}).join('')+'</div>':empty('No recovery work','The recovery engine will populate this view when revenue opportunities are identified.'))+'</div></div>';}
  function intelligence(){var total=state.opportunities.reduce(function(n,o){return n+Number(o.amount||0);},0);return '<div class="page">'+head('INTELLIGENCE','Revenue Intelligence','Understand where revenue is leaking and what needs attention.')+'<div class="grid4">'+kpi('Identified',money(total),'Current opportunity value','Live','◉')+kpi('Recovered',money(state.recovered),'Recorded recovery','Live','✓')+kpi('Signals',String(state.looseEnds.length),'Open recovery signals','Live','✦')+kpi('At risk',money(Math.round(total*1.25)),'Planning estimate, not booked revenue','Model','!')+'</div><div style="margin-top:14px">'+empty('Intelligence layer is connected','Automations and recovery rules can turn live records into prioritized next actions. Review Automations to configure them.')+'</div></div>';}
  function settings(){var p=window.LOSMB&&LOSMB.getProfile?LOSMB.getProfile():null;return '<div class="page">'+head('CONTROL PLANE','Settings','Business identity, workspace configuration, integrations, automation, and security.')+'<div class="card settings"><div class="setting-row"><div><strong>Business profile</strong><p>'+(p&&p.name?esc(p.name):'Configure your business name and type.')+'</p></div><button class="action secondary" onclick="LE.business()">Edit</button></div><div class="setting-row"><div><strong>Workspace</strong><p>'+(state.workspaceId?esc(state.workspaceId):'Not connected')+'</p></div><span class="status">'+(state.loaded?'Connected':'Pending')+'</span></div><div class="setting-row"><div><strong>Automation</strong><p>Workflow Center is available from the Automations navigation.</p></div><button class="action secondary" onclick="LE.automations()">Open</button></div><div class="setting-row"><div><strong>Data</strong><p>All primary records are loaded from the signed-in workspace.</p></div><button class="action secondary" onclick="LE.refresh()">Refresh</button></div></div></div>';}
  function render(){if(!content)return;var v=state.view;if(v==='overview')content.innerHTML=dashboard();else if(v==='loose')content.innerHTML=loose();else if(v==='customers')content.innerHTML=customers();else if(v==='recovery')content.innerHTML=recovery();else if(v==='intelligence')content.innerHTML=intelligence();else if(v==='settings')content.innerHTML=settings();else content.innerHTML=dashboard();document.querySelectorAll('.nav-item').forEach(function(n){n.classList.toggle('active',n.getAttribute('data-view')===state.view);});var q=document.getElementById('queueSearch');if(q)q.addEventListener('input',function(){state.query=this.value;persist();render();});}
  function setView(v){state.view=v;persist();render();window.scrollTo(0,0);}
  function openOpp(id){var o=state.opportunities.find(function(x){return String(x.id)===String(id);});if(!o)return;var d=document.querySelector('.drawer');if(!d)return;d.innerHTML='<div class="drawer-head"><div class="eyebrow">LIVE OPPORTUNITY</div><button class="close" onclick="LE.close()">×</button></div><h2>'+esc(o.customer)+'</h2><div class="muted">'+esc(o.type)+' · '+esc(o.status)+'</div><div class="detail-amount">'+money(o.amount)+'</div><div class="detail-grid"><div class="detail-box"><label>Priority</label><strong>'+esc(o.priority)+'</strong></div><div class="detail-box"><label>Source</label><strong>'+esc(o.source)+'</strong></div></div><div class="recommend"><b>✦ NEXT BEST ACTION</b><p>'+esc(o.next)+'</p></div><div class="detail-box"><label>Why this is open</label><strong style="line-height:1.5">'+esc(o.reason)+'</strong></div><div class="drawer-actions"><button onclick="LE.recover(\''+esc(o.id)+'\')">Mark recovered</button><button class="secondary" onclick="LE.followUp(\''+esc(o.id)+'\')">Create follow-up</button></div>';document.getElementById('drawer').classList.remove('hidden');}
  function close(){var d=document.getElementById('drawer');if(d)d.classList.add('hidden');}
  async function recover(id){var o=state.opportunities.find(function(x){return String(x.id)===String(id);});if(!o)return;if(!SB||!state.workspaceId){toast('Workspace connection required');return;}try{var now=new Date().toISOString(),r;if(o.opportunityId)r=await SB.from('opportunities').update({status:'recovered',recovered_amount:Number(o.amount||0),recovered_at:now,updated_at:now}).eq('id',o.opportunityId).eq('workspace_id',state.workspaceId);else if(o.looseId)r=await SB.from('loose_ends').update({status:'recovered',recovered_amount:Number(o.amount||0),recovery_stage:'collected',last_action_at:now,last_action:'recovered',updated_at:now}).eq('id',o.looseId).eq('workspace_id',state.workspaceId);else throw new Error('Opportunity record is not linked to a recoverable database row');if(r.error)throw r.error;toast(money(o.amount)+' marked recovered');close();await refresh();}catch(e){toast('Could not record recovery: '+(e.message||'unknown error'));}}
  async function followUp(id){var o=state.opportunities.find(function(x){return String(x.id)===String(id);});if(!o||!SB||!state.workspaceId){toast('Workspace connection required');return;}try{var r=await SB.from('follow_ups').insert({workspace_id:state.workspaceId,customer_id:o.customerId||null,opportunity_id:o.opportunityId||null,channel:'task',status:'pending',scheduled_at:new Date(Date.now()+86400000).toISOString(),message:o.reason||'Follow up on revenue opportunity'});if(r.error)throw r.error;toast('Follow-up created');close();await refresh();}catch(e){toast('Could not create follow-up: '+(e.message||'unknown error'));}}
  function contact(){toast('Use the customer contact details or a configured communication integration.');}
  function business(){toast('Business profile is managed in Settings.');}
  function automations(){var b=document.querySelector('[data-view="automations"]');if(b)b.click();else toast('Open Automations from the navigation.');}
  loadLocal();
  window.LE={setView:setView,openOpp:openOpp,close:close,recover:recover,followUp:followUp,contact:contact,business:business,refresh:refresh,automations:automations,supabase:SB,getState:function(){return state;}};
  window.setView=setView;
  content=document.getElementById('content');
  if(content){var note=document.querySelector('.demo-note');if(note)note.innerHTML='LIVE WORKSPACE<br><span>Sign in or create your business account</span>';var shop=document.getElementById('businessSwitcher');if(shop)shop.innerHTML='Business <small>Workspace</small>⌄';var av=document.getElementById('businessAvatar');if(av)av.textContent='LE';document.querySelectorAll('.nav-item').forEach(function(n){n.addEventListener('click',function(){setView(n.getAttribute('data-view'));});});var s=document.getElementById('globalSearch');if(s)s.addEventListener('input',function(){state.query=this.value||'';if(this.value)state.view='loose';persist();render();});var backdrop=document.querySelector('.backdrop');if(backdrop)backdrop.addEventListener('click',close);render();refresh();}
})();