/* Loose Ends live workspace bridge: Supabase Auth + workspace bootstrap + live data sync. */
(function(){
  'use strict';
  var S=window.LESupabase;
  if(!S) return;
  var KEY='loose_ends_v31_state', MAP='loose_ends_live_map';
  var sessionUser=null, workspace=null, live=false, demoSnapshot=null;
  function esc(s){return String(s||'').replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c];});}
  function toast(m){var e=document.getElementById('toast');if(e){e.textContent=m;e.className='toast show';setTimeout(function(){e.className='toast';},2200)}}
  function setPill(){var p=document.getElementById('le-auth-pill');if(!p)return;p.innerHTML=live?'● LIVE · '+esc(workspace?workspace.name:'Workspace'):'◌ DEMO MODE';p.className='le-auth-pill '+(live?'live':'demo');}
  function styles(){if(document.getElementById('le-auth-css'))return;var s=document.createElement('style');s.id='le-auth-css';s.textContent='.le-auth-pill{position:fixed;right:18px;top:14px;z-index:10050;border:1px solid rgba(255,255,255,.12);background:#111827;color:#fff;padding:8px 12px;border-radius:999px;font:700 11px/1 system-ui;letter-spacing:.08em;cursor:pointer;box-shadow:0 8px 24px rgba(0,0,0,.18)}.le-auth-pill.live{background:#0b3b31;border-color:#27c59a;color:#b9ffe8}.le-auth-pill.demo{background:#222a38}.le-auth-modal{position:fixed;inset:0;z-index:10060;background:rgba(4,8,15,.72);backdrop-filter:blur(8px);display:flex;align-items:center;justify-content:center;padding:18px}.le-auth-card{width:min(440px,100%);background:#fff;border:1px solid #e5e7eb;border-radius:22px;padding:26px;box-shadow:0 30px 90px rgba(0,0,0,.3)}.le-auth-card h2{margin:0 0 6px;font:800 26px/1.1 system-ui;color:#101828}.le-auth-card p{color:#667085;margin:0 0 20px}.le-auth-field{display:block;font:700 12px system-ui;color:#344054;margin:12px 0 6px}.le-auth-input{width:100%;box-sizing:border-box;padding:13px 14px;border:1px solid #d0d5dd;border-radius:12px;font:500 15px system-ui}.le-auth-actions{display:flex;gap:10px;margin-top:18px}.le-auth-btn{flex:1;border:0;border-radius:12px;padding:13px 15px;font:800 14px system-ui;cursor:pointer}.le-auth-primary{background:#101828;color:#fff}.le-auth-secondary{background:#f2f4f7;color:#344054}.le-auth-note{min-height:18px;margin-top:12px;font:600 12px system-ui;color:#667085}.le-auth-close{float:right;border:0;background:none;font-size:26px;cursor:pointer;color:#667085}.le-auth-lock{font-size:12px;color:#667085;margin-top:12px}.le-live-banner{position:fixed;left:18px;bottom:18px;z-index:10040;background:#0b3b31;color:#b9ffe8;border:1px solid #27c59a;border-radius:14px;padding:10px 13px;font:700 11px system-ui;box-shadow:0 12px 32px rgba(0,0,0,.2)}@media(max-width:700px){.le-auth-pill{right:10px;top:10px}.le-live-banner{left:10px;bottom:76px}}';document.head.appendChild(s)}
  function pill(){var p=document.createElement('button');p.id='le-auth-pill';p.onclick=openAuth;p.setAttribute('aria-label','Account and live mode');document.body.appendChild(p);setPill()}
  function openAuth(){var old=document.getElementById('le-auth-modal');if(old)old.remove();var d=document.createElement('div');d.id='le-auth-modal';d.className='le-auth-modal';d.innerHTML='<div class="le-auth-card"><button class="le-auth-close" onclick="document.getElementById(\'le-auth-modal\').remove()">×</button><div class="eyebrow">LOOSE ENDS</div><h2>'+(sessionUser?'Live workspace':'Turn demo into your workspace')+'</h2><p>'+(sessionUser?'Your account is connected. Live data is isolated to your workspace.':'Create an account to save real customers, opportunities, follow-ups, and recovery events.')+'</p>'+(sessionUser?'<div class="le-auth-user"><div><strong>'+esc(sessionUser.email)+'</strong><small>Signed in</small></div><button class="le-auth-btn le-auth-secondary" onclick="LELive.signOut()">Sign out</button></div><div class="le-auth-lock">Secure browser session · database access protected by Supabase Auth + RLS.</div>':'<form id="le-auth-form"><label class="le-auth-field">Email</label><input class="le-auth-input" name="email" type="email" autocomplete="email" required placeholder="you@business.com"><label class="le-auth-field">Password</label><input class="le-auth-input" name="password" type="password" minlength="8" autocomplete="current-password" required placeholder="At least 8 characters"><div class="le-auth-actions"><button class="le-auth-btn le-auth-primary" type="submit">Sign in</button><button class="le-auth-btn le-auth-secondary" type="button" id="le-signup">Create account</button></div><div class="le-auth-note" id="le-auth-note">Use Sign in for an existing account, or Create account for a new workspace.</div></form>')+'</div>';document.body.appendChild(d);var f=document.getElementById('le-auth-form');if(f)f.addEventListener('submit',function(e){e.preventDefault();auth(false,f)});var su=document.getElementById('le-signup');if(su)su.addEventListener('click',function(){auth(true,document.getElementById('le-auth-form'))})}
  async function auth(signup,f){var note=document.getElementById('le-auth-note');var email=f.email.value.trim(),password=f.password.value;if(note)note.textContent=signup?'Creating your account…':'Signing you in…';var r=signup?await S.auth.signUp({email:email,password:password}):await S.auth.signInWithPassword({email:email,password:password});if(r.error){if(note)note.textContent=r.error.message;return}if(signup&&!r.data.session){if(note)note.textContent='Account created. Check your email to confirm, then sign in.';return}await bootSession();var m=document.getElementById('le-auth-modal');if(m)m.remove()}
  async function bootSession(){var r=await S.auth.getUser();sessionUser=r.data&&r.data.user;if(!sessionUser){live=false;workspace=null;setPill();return}var q=await S.from('workspace_members').select('workspace_id,role,workspaces(*)').eq('user_id',sessionUser.id).limit(1).maybeSingle();if(q.error){console.warn(q.error);toast('Could not load workspace');return}if(!q.data){var rr=await S.functions.invoke('bootstrap-workspace',{body:{name:'My Business',slug:'my-business-'+sessionUser.id.replaceAll('-','').slice(0,8)}});if(rr.error){toast(rr.error.message||'Could not create workspace');return}workspace=rr.data.workspace}else workspace=q.data.workspaces;live=true;setPill();await loadLive()}
  async function loadLive(){if(!workspace)return;demoSnapshot=JSON.parse(localStorage.getItem(KEY)||'null');var c=await S.from('customers').select('*').eq('workspace_id',workspace.id).order('created_at',{ascending:false});var o=await S.from('opportunities').select('*,customers(*)').eq('workspace_id',workspace.id).in('status',['open','contacted','scheduled']).order('amount',{ascending:false});if(c.error||o.error){toast('Live data could not be loaded');return}var opps=(o.data||[]).map(function(x,i){var cu=x.customers||{};return{id:i+1,uuid:x.id,type:x.title||x.source||'Opportunity',cls:classFor(x.source),customer:((cu.first_name||'')+' '+(cu.last_name||'')).trim()||'Customer',phone:cu.phone||'',vehicle:cu.notes||'Customer record',amount:Number(x.amount||0),priority:Number(x.priority||0)>=80?'High':Number(x.priority||0)>=50?'Medium':'Low',source:x.source||'Imported',reason:x.reason||'Revenue opportunity identified.',next:'Review this opportunity and contact the customer.',message:'Hi '+(cu.first_name||'there')+', this is your business following up on your recent service.'}});var ids={};(o.data||[]).forEach(function(x,i){ids[i+1]=x.id});localStorage.setItem(MAP,JSON.stringify(ids));var old=JSON.parse(localStorage.getItem(KEY)||'{}')||{};old.view=old.view||'overview';old.query='';old.opps=opps;old.recovered=0;old.activities=[];old.followUps=[];localStorage.setItem(KEY,JSON.stringify(old));if(window.LE&&window.LE.setView)window.LE.setView(old.view);var b=document.getElementById('le-live-banner');if(!b){b=document.createElement('div');b.id='le-live-banner';b.className='le-live-banner';b.textContent='LIVE DATA · '+(o.data||[]).length+' active opportunities';document.body.appendChild(b)}}
  function classFor(s){s=String(s||'').toLowerCase();if(s.indexOf('declin')>=0)return'red';if(s.indexOf('miss')>=0)return'purple';if(s.indexOf('dorm')>=0)return'blue';return'amber'}
  async function signOut(){await S.auth.signOut();live=false;workspace=null;sessionUser=null;var snap=demoSnapshot;if(snap)localStorage.setItem(KEY,JSON.stringify(snap));setPill();var m=document.getElementById('le-auth-modal');if(m)m.remove();location.reload()}
  async function syncRecover(id){var map=JSON.parse(localStorage.getItem(MAP)||'{}'),uuid=map[id];if(!uuid||!workspace)return;var opp=(await S.from('opportunities').select('id,workspace_id,customer_id,amount').eq('id',uuid).eq('workspace_id',workspace.id).maybeSingle()).data;if(!opp)return;var amt=Number(opp.amount||0);var u=await S.from('opportunities').update({status:'recovered',recovered_amount:amt,recovered_at:new Date().toISOString()}).eq('id',uuid).eq('workspace_id',workspace.id);if(u.error){toast(u.error.message);return}await S.from('recovery_events').insert({workspace_id:workspace.id,opportunity_id:uuid,customer_id:opp.customer_id,amount:amt,source:'dashboard',note:'Marked recovered in Loose Ends'});toast('Saved to live workspace')}
  function wrap(){if(!window.LE||window.LELiveWrapped)return;if(window.LE.recover){var orig=window.LE.recover;window.LE.recover=function(id){if(live)syncRecover(id);return orig(id)}}window.LELiveWrapped=true}
  window.LELive={openAuth:openAuth,signOut:signOut,loadLive:loadLive};styles();pill();wrap();S.auth.onAuthStateChange(function(){setTimeout(bootSession,0)});bootSession();
})();
