/* Loose Ends Workflow Engine — horizontal automation layer. */
(function(){
  'use strict';
  var KEY='loose_ends_workflows_v1';
  var recipes=[
    {name:'Recover stale opportunities',description:'Create a follow-up when an open opportunity has gone untouched.',trigger_type:'record_updated',trigger_config:{entity_type:'opportunities'},conditions:[{field:'status',operator:'equals',value:'open'}],actions:[{type:'create_follow_up',channel:'task',message:'Review and follow up on this opportunity.',delay_hours:0}],mode:'approval'},
    {name:'Welcome new customers',description:'Create an onboarding task whenever a customer is created.',trigger_type:'record_created',trigger_config:{entity_type:'customers'},conditions:[],actions:[{type:'create_task',title:'Welcome new customer',priority:2,delay_hours:0}],mode:'automatic'},
    {name:'Appointment follow-up',description:'Create a next-step task after an appointment is completed.',trigger_type:'record_updated',trigger_config:{entity_type:'appointments'},conditions:[{field:'status',operator:'equals',value:'completed'}],actions:[{type:'create_task',title:'Follow up after completed appointment',priority:1,delay_hours:24}],mode:'automatic'},
    {name:'Overdue invoice alert',description:'Flag an overdue invoice for the owner to review.',trigger_type:'record_updated',trigger_config:{entity_type:'documents'},conditions:[{field:'document_type',operator:'equals',value:'invoice'},{field:'status',operator:'equals',value:'overdue'}],actions:[{type:'create_task',title:'Review overdue invoice',priority:3,delay_hours:0}],mode:'approval'}
  ];
  var state={workflows:[],pendingRuns:[],recentRuns:[]};
  var runnerBusy=false;
  function esc(s){return String(s==null?'':s).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c];});}
  function toast(m){var e=document.getElementById('toast');if(e){e.textContent=m;e.className='toast show';setTimeout(function(){e.className='toast';},2200);}}
  function loadLocal(){try{var x=JSON.parse(localStorage.getItem(KEY)||'null');if(x&&Array.isArray(x.workflows))state.workflows=x.workflows;}catch(e){}}
  function saveLocal(){try{localStorage.setItem(KEY,JSON.stringify({workflows:state.workflows}));}catch(e){}}
  function client(){return window.LESupabase||null;}
  async function workspaceId(){var c=client();if(!c)return null;var u=await c.auth.getUser();var uid=u.data&&u.data.user&&u.data.user.id;if(!uid)return null;var m=await c.from('workspace_members').select('workspace_id').eq('user_id',uid).limit(1).maybeSingle();return m.data&&m.data.workspace_id||null;}
  async function runner(body){var c=client();if(!c||!c.auth)return null;var session=await c.auth.getSession();var token=session.data&&session.data.session&&session.data.session.access_token;if(!token)return null;var base=(window.__LOOSE_ENDS_SUPABASE_URL__||'').replace(/\/$/,'');if(!base)return null;var res=await fetch(base+'/functions/v1/workflow-runner',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify(body||{})});var json=await res.json().catch(function(){return {};});if(!res.ok)throw new Error(json.error||'Workflow runner failed');return json;}
  async function refreshRuns(){var c=client(),w=await workspaceId();if(!c||!w){state.pendingRuns=[];state.recentRuns=[];return;}var r=await c.from('workflow_runs').select('id,workflow_id,status,context,error,created_at,started_at,completed_at,approved_by').eq('workspace_id',w).order('created_at',{ascending:false}).limit(30);if(r.error)return;state.pendingRuns=(r.data||[]).filter(function(x){return x.status==='waiting_approval';});state.recentRuns=(r.data||[]).slice(0,12);}
  async function pump(){if(runnerBusy)return;var c=client();if(!c)return;var u=await c.auth.getUser();if(!u.data||!u.data.user)return;runnerBusy=true;try{await runner({});await refreshRuns();render();}catch(e){}finally{runnerBusy=false;}}
  async function load(){loadLocal();var c=client(),w=await workspaceId();if(c&&w){var r=await c.from('workflows').select('*').eq('workspace_id',w).order('created_at',{ascending:false});if(!r.error&&r.data)state.workflows=r.data;}await refreshRuns();render();pump();}
  async function persist(wf,existingId){var c=client(),w=await workspaceId(),saved=wf;if(c&&w){var payload=Object.assign({},wf,{workspace_id:w,updated_at:new Date().toISOString()});var r=existingId?await c.from('workflows').update(payload).eq('id',existingId).eq('workspace_id',w).select().single():await c.from('workflows').insert(payload).select().single();if(r.error){toast('Could not save workflow');return;}saved=r.data;}if(existingId){var idx=state.workflows.findIndex(function(x){return x.id===existingId;});if(idx>=0)state.workflows[idx]=saved;else state.workflows.unshift(saved);}else{state.workflows.unshift(saved);}saveLocal();render();toast(existingId?'Workflow updated':'Workflow created');}
  async function installRecipe(recipe){var existing=state.workflows.find(function(x){return x.name===recipe.name;});if(existing){toast('Recipe already installed');openEditor(existing);return;}await persist(Object.assign({},recipe,{enabled:true}));}
  async function toggleWorkflow(id,enabled){var c=client(),w=await workspaceId();if(c&&w&&id){var r=await c.from('workflows').update({enabled:enabled,updated_at:new Date().toISOString()}).eq('id',id).eq('workspace_id',w);if(r.error){toast('Could not update workflow');return;}}var wf=state.workflows.find(function(x){return x.id===id;});if(wf)wf.enabled=enabled;saveLocal();render();}
  async function approveRun(id){try{toast('Running approved automation…');var result=await runner({approve_run_id:id});toast(result&&result.status==='completed'?'Automation completed':'Automation updated');await refreshRuns();render();}catch(e){toast(e.message||'Could not approve automation');}}
  function runRow(run){var wf=state.workflows.find(function(x){return x.id===run.workflow_id;});var name=wf?wf.name:'Workflow';var rec=run.context&&run.context.record||{};var subject=rec.name||rec.title||rec.email||rec.id||'record';var cls=run.status==='completed'?'done':(run.status==='failed'?'bad':'');return '<div class="wf-row '+cls+'"><div><strong>'+esc(name)+'</strong><small>'+esc(subject)+' · '+esc(new Date(run.created_at).toLocaleString())+(run.error?' · '+esc(run.error):'')+'</small></div><span class="wf-pill">'+esc(run.status||'unknown')+'</span>'+(run.status==='waiting_approval'?'<button class="action primary" data-approve="'+esc(run.id)+'">Approve & run</button>':'')+'</div>';}
  function workflowRow(w,i){return '<div class="wf-row"><div><strong>'+esc(w.name)+'</strong><small>'+esc(w.description||'')+' · '+esc((w.trigger_type||'manual'))+' · '+esc(((w.actions||[]).length)+' action'+((w.actions||[]).length===1?'':'s'))+'</small></div><span class="wf-pill">'+esc(w.mode||'manual')+'</span><span class="wf-status '+(w.enabled===false?'off':'')+'">'+(w.enabled===false?'Off':'Active')+'</span><button class="action" data-edit="'+i+'">Edit</button><button class="action" data-toggle="'+i+'">'+(w.enabled===false?'Enable':'Disable')+'</button></div>';}
  function render(){var page=document.querySelector('#content .page');if(!page)return;var old=document.getElementById('workflowCenter');if(old)old.remove();var box=document.createElement('section');box.id='workflowCenter';box.className='workflow-center';var pending=state.pendingRuns.length;box.innerHTML='<div class="wf-head"><div><div class="eyebrow">AUTOMATION ENGINE</div><h2>Workflows</h2><p>Build repeatable business processes once. Loose Ends watches records, evaluates rules, runs safe actions, and keeps an audit trail.</p></div><button id="wfCreate" class="primary">Create workflow</button></div>'+(pending?'<div class="card section-card wf-approval"><div class="section-head"><div><div class="section-title">Needs approval <span class="wf-count">'+pending+'</span></div><div class="section-sub">These automations are waiting for a human before taking action.</div></div></div>'+state.pendingRuns.map(runRow).join('')+'</div>':'')+'<div class="wf-grid"><div class="card section-card"><div class="section-head"><div><div class="section-title">Active automations</div><div class="section-sub">Shared across CRM, work, scheduling, billing, and recovery.</div></div></div>'+(state.workflows.length?state.workflows.map(workflowRow).join(''):'<div class="wf-empty">No workflows yet. Start with a proven recipe below.</div>')+'</div><div class="card section-card"><div class="section-head"><div><div class="section-title">Run history</div><div class="section-sub">Recent automation outcomes and failures.</div></div></div>'+(state.recentRuns.length?state.recentRuns.map(runRow).join(''):'<div class="wf-empty">No runs yet.</div>')+'</div></div><div class="card section-card"><div class="section-head"><div><div class="section-title">Recipe library</div><div class="section-sub">Install once; repeated clicks do not create duplicates.</div></div></div>'+recipes.map(function(r,i){return '<div class="wf-recipe"><div><strong>'+esc(r.name)+'</strong><small>'+esc(r.description)+'</small></div><button class="action" data-recipe="'+i+'">Use recipe</button></div>';}).join('')+'</div>';
    page.appendChild(box);
    document.getElementById('wfCreate').onclick=function(){openEditor();};
    box.querySelectorAll('[data-recipe]').forEach(function(b){b.onclick=function(){installRecipe(recipes[Number(b.dataset.recipe)]);};});
    box.querySelectorAll('[data-approve]').forEach(function(b){b.onclick=function(){approveRun(b.dataset.approve);};});
    box.querySelectorAll('[data-edit]').forEach(function(b){b.onclick=function(){openEditor(state.workflows[Number(b.dataset.edit)]);};});
    box.querySelectorAll('[data-toggle]').forEach(function(b){b.onclick=function(){var wf=state.workflows[Number(b.dataset.toggle)];toggleWorkflow(wf.id,wf.enabled===false);};});
  }
  function conditionEditor(conditions){var c=(conditions&&conditions[0])||{};return '<div class="wf-subsection"><div class="section-title">Condition</div><div class="wf-fields"><input id="wfCondField" class="input" placeholder="Field (e.g. status)" value="'+esc(c.field||'')+'"><select id="wfCondOp" class="input"><option value="equals">equals</option><option value="not_equals">not equals</option><option value="contains">contains</option><option value="exists">exists</option><option value="gt">greater than</option><option value="gte">at least</option><option value="lt">less than</option><option value="lte">at most</option></select><input id="wfCondValue" class="input" placeholder="Value" value="'+esc(c.value||'')+'"></div><small>Leave the field blank for no condition. Additional conditions can be added through the workflow data model without changing the runner contract.</small></div>';}
  function openEditor(seed){var d=document.getElementById('drawer');if(!d)return;var w=seed||{name:'',description:'',enabled:true,mode:'approval',trigger_type:'manual',trigger_config:{},conditions:[],actions:[]};var a=(w.actions||[])[0]||{};var tc=w.trigger_config||{};d.classList.remove('hidden');var dr=d.querySelector('.drawer');dr.innerHTML='<div class="drawer-head"><div><div class="eyebrow">WORKFLOW</div><h2>'+(w.id?'Edit workflow':'New workflow')+'</h2></div><button class="icon-btn" id="wfClose">×</button></div><div class="drawer-body"><label>Name<input id="wfName" class="input" value="'+esc(w.name||'')+'"></label><label>Description<textarea id="wfDesc" class="input">'+esc(w.description||'')+'</textarea></label><label>Trigger<select id="wfTrigger" class="input"><option value="manual">Manual</option><option value="record_created">Record created</option><option value="record_updated">Record updated</option><option value="record_due">Record due</option><option value="schedule">Schedule</option></select></label><label>Mode<select id="wfMode" class="input"><option value="automatic">Automatic</option><option value="approval">Approval required</option><option value="manual">Manual</option></select></label><label>Entity<input id="wfEntity" class="input" placeholder="customers, opportunities, appointments, documents" value="'+esc(tc.entity_type||'')+'"></label><label>Schedule interval (minutes)<input id="wfInterval" type="number" min="1" class="input" value="'+esc(tc.interval_minutes||60)+'"></label>'+conditionEditor(w.conditions)+'<label>Action<select id="wfAction" class="input"><option value="create_task">Create task</option><option value="create_follow_up">Create follow-up</option><option value="update_opportunity">Update opportunity</option></select></label><label>Action title/message<input id="wfActionText" class="input" value="'+esc(a.title||a.message||'Review and take the next best action')+'"></label><label>Delay (hours)<input id="wfDelay" type="number" min="0" class="input" value="'+esc(a.delay_hours||0)+'"></label><button id="wfSave" class="primary">Save workflow</button></div>';
    document.getElementById('wfTrigger').value=w.trigger_type||'manual';document.getElementById('wfMode').value=w.mode||'approval';document.getElementById('wfAction').value=a.type||'create_task';document.getElementById('wfCondOp').value=(w.conditions&&w.conditions[0]&&w.conditions[0].operator)||'equals';document.getElementById('wfClose').onclick=function(){d.classList.add('hidden');};
    document.getElementById('wfSave').onclick=function(){var trigger=document.getElementById('wfTrigger').value,entity=document.getElementById('wfEntity').value.trim(),interval=Number(document.getElementById('wfInterval').value||60);if(trigger!=='manual'&&!entity){toast('Entity is required for this trigger');return;}if(trigger==='schedule'&&interval<1){toast('Schedule interval must be at least 1 minute');return;}var action=document.getElementById('wfAction').value,text=document.getElementById('wfActionText').value||'Review and take the next best action';var aa={type:action,delay_hours:Number(document.getElementById('wfDelay').value||0)};if(action==='create_task')Object.assign(aa,{title:text,priority:2});else if(action==='create_follow_up')Object.assign(aa,{channel:'task',message:text});else Object.assign(aa,{patch:{status:text}});var field=document.getElementById('wfCondField').value.trim(),conditions=field?[{field:field,operator:document.getElementById('wfCondOp').value,value:document.getElementById('wfCondValue').value}]:[];var payload={name:document.getElementById('wfName').value.trim()||'Untitled workflow',description:document.getElementById('wfDesc').value.trim(),enabled:w.enabled!==false,mode:document.getElementById('wfMode').value,trigger_type:trigger,trigger_config:{entity_type:entity,interval_minutes:interval},conditions:conditions,actions:[aa]};persist(payload,w.id||null);d.classList.add('hidden');};
  }
  function show(){var content=document.getElementById('content');if(!content)return;content.innerHTML='<div class="page"><div class="page-head"><div><div class="eyebrow">AUTOMATION</div><div class="title">Workflow Center</div><div class="subtitle">Automate the work between lead, customer, appointment, job, invoice, payment, and recovery.</div></div><div class="date">Automation engine</div></div></div>';setTimeout(render,0);document.querySelectorAll('.nav-item').forEach(function(n){n.classList.toggle('active',n.dataset.view==='workflows');});}
  function addNav(){var nav=document.querySelector('nav');if(!nav||nav.querySelector('[data-view="workflows"]'))return;var b=document.createElement('button');b.type='button';b.className='nav-item';b.dataset.view='workflows';b.innerHTML='<span>⚡</span>Automations';b.onclick=function(){show();load();};nav.appendChild(b);}
  function init(){addNav();loadLocal();var old=window.LE&&LE.setView;if(old&&!old.__wfWrapped){var wrap=function(v){if(v==='workflows'){show();load();return;}old(v);};wrap.__wfWrapped=true;window.LE.setView=wrap;}setInterval(function(){pump();},30000);}
  window.LEWorkflows={load:load,create:persist,recipes:recipes,approve:approveRun,pump:pump};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();